[border]
width=3
radius=7

[colors]
background=282828ff
input=ebdbb2ff
prompt=665c54ff
text=ebdbb2ff
selection=3c3836ff
selection-text=ebdbb2ff
match=7c6f64ff
border=504945ff
selection-match=fabd2fff

[main]
font=JetBrainsMono Nerd Font:size=9
prompt="  "
terminal=alacritty
icons-enabled=no

# layout
width=20
lines=4
horizontal-pad=16
vertical-pad=10
inner-pad=4

# behavior
layer=overlay
exit-on-keyboard-focus-loss=yes

# position (closest to --center behavior)
anchor=center

# performance/UX
dpi-aware=yes
